[build-system]
requires = [
    "setuptools"
    ]
build-backend = "setuptools.build_meta"

[project]
name = "yastn-benchmarks"
version = "0.1.0"
description = "Benchmarks for YASTN tensor network library"
authors = [
    { name="The YASTN Authors" }
]
requires-python = ">=3.10"
dependencies = [
    "yastn @ git+https://github.com/yastn/yastn.git@7f2d03ec338455dffd25c210d2d261c1cb764b66",
    "nvtx"
]